<a href="https://colab.research.google.com/github/01-slime/Standardzation/blob/main/%EF%BC%B4%E5%A4%A7%E4%BD%BF%E4%BC%81%E6%A5%AD%E5%AF%A6%E4%BD%9C_%E7%AC%AC%E4%B8%80%E9%80%B1%E4%BD%9C%E6%A5%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Z-score

###import package

In [7]:
import numpy as np
from scipy import stats

In [8]:
data = np.array([200,300,400,600,1000])
data

array([ 200,  300,  400,  600, 1000])

In [9]:
#看型態 #array=陣列
type(data)

numpy.ndarray

In [10]:
zscore = stats.zscore(data)
zscore

array([-1.06066017, -0.70710678, -0.35355339,  0.35355339,  1.76776695])

### Min-Max

### import package

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

minmax = scaler.fit_transform(data)

ValueError: ignored

In [19]:
data.shape #看維度 #上述出錯因為要用二維，檢查維度： Roll,Caler...

(5,)

In [21]:
#重做
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data2 =np.array([[200],[300],[400],[600],[1000]])
data2

array([[ 200],
       [ 300],
       [ 400],
       [ 600],
       [1000]])

In [24]:
data2.shape #roll是5 column是1

(5, 1)

In [26]:
minmax = scaler.fit_transform(data2)
minmax

array([[0.   ],
       [0.125],
       [0.25 ],
       [0.5  ],
       [1.   ]])